# Generated by Django 5.0 on 2024-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_message_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('delivered', 'delivered'), ('shipped', 'shipped'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=50),
        ),
    ]
