# Generated by Django 5.0 on 2024-01-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
